- name: Build and Publish Docker Image

  on:
    push:
      branches:
        - main #当代码推送到主分支时触发

  jobs:
    build:
      runs-on: ubuntu-lates
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t dtest/dtest001:latest .

      - name: Push Docker image to Docker Hub
          uses: docker/login-action@v1
          with:
            DOCKER_USER: ${{ secrets.DTEST_NAME }}
            DOCKER_TOKEN: ${{ secrets.DTEST_TOKEN }}
      -run: docker push dtest/dtest001:latest .